### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wandersoncferreira** [green-coder/minimallist#1]
Hello @green-coder how are you? Very nice library this one. Congrats! I am contributing with spec-tools for a while now and I like this subject. Are you planning to work alone in this project or there are plans to onboard new people?

I would like to contribute with some code in spare time if possible. A road map of future enhancements and ideas would be very welcome to understand where are you heading!

Cheers!

**Comment by green-coder** [comment]
hello @wandersoncferreira, thank for the feedback. I prefer to work alone on this project at the moment.

The roadmap and timeline will depend on the needs of the [vrac](https://github.com/green-coder/vrac) project - minimallist was implemented because of it (see https://github.com/green-coder/vrac/issues/3)

If you have something specific in mind as a contribution, let me know.
